// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Niche struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	Summary         string    `json:"summary"`
	AudienceRegions []string  `json:"audience_regions"`
	SeedKeywords    []string  `json:"seed_keywords"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type WorkflowEvent struct {
	ID            int64           `json:"id"`
	WorkflowRunID int64           `json:"workflow_run_id"`
	EventType     string          `json:"event_type"`
	Message       string          `json:"message"`
	Payload       json.RawMessage `json:"payload"`
	CreatedAt     time.Time       `json:"created_at"`
}

type WorkflowRun struct {
	ID           int64                 `json:"id"`
	NicheID      sql.NullInt64         `json:"niche_id"`
	WorkflowType string                `json:"workflow_type"`
	Status       string                `json:"status"`
	Input        json.RawMessage       `json:"input"`
	Output       pqtype.NullRawMessage `json:"output"`
	ErrorMessage sql.NullString        `json:"error_message"`
	StartedAt    sql.NullTime          `json:"started_at"`
	FinishedAt   sql.NullTime          `json:"finished_at"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}
