// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: niches.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const createNiche = `-- name: CreateNiche :one
INSERT INTO niches (
    name,
    summary,
    audience_regions,
    seed_keywords,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, summary, audience_regions, seed_keywords, status, created_at, updated_at
`

type CreateNicheParams struct {
	Name            string   `json:"name"`
	Summary         string   `json:"summary"`
	AudienceRegions []string `json:"audience_regions"`
	SeedKeywords    []string `json:"seed_keywords"`
	Status          string   `json:"status"`
}

func (q *Queries) CreateNiche(ctx context.Context, arg CreateNicheParams) (Niche, error) {
	row := q.db.QueryRowContext(ctx, createNiche,
		arg.Name,
		arg.Summary,
		pq.Array(arg.AudienceRegions),
		pq.Array(arg.SeedKeywords),
		arg.Status,
	)
	var i Niche
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Summary,
		pq.Array(&i.AudienceRegions),
		pq.Array(&i.SeedKeywords),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNiche = `-- name: GetNiche :one
SELECT id, name, summary, audience_regions, seed_keywords, status, created_at, updated_at
FROM niches
WHERE id = $1
`

func (q *Queries) GetNiche(ctx context.Context, id int64) (Niche, error) {
	row := q.db.QueryRowContext(ctx, getNiche, id)
	var i Niche
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Summary,
		pq.Array(&i.AudienceRegions),
		pq.Array(&i.SeedKeywords),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNiches = `-- name: ListNiches :many
SELECT id, name, summary, audience_regions, seed_keywords, status, created_at, updated_at
FROM niches
ORDER BY name
`

func (q *Queries) ListNiches(ctx context.Context) ([]Niche, error) {
	rows, err := q.db.QueryContext(ctx, listNiches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Niche{}
	for rows.Next() {
		var i Niche
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Summary,
			pq.Array(&i.AudienceRegions),
			pq.Array(&i.SeedKeywords),
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNicheStatus = `-- name: UpdateNicheStatus :one
UPDATE niches
SET status = $2
WHERE id = $1
RETURNING id, name, summary, audience_regions, seed_keywords, status, created_at, updated_at
`

type UpdateNicheStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNicheStatus(ctx context.Context, arg UpdateNicheStatusParams) (Niche, error) {
	row := q.db.QueryRowContext(ctx, updateNicheStatus, arg.ID, arg.Status)
	var i Niche
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Summary,
		pq.Array(&i.AudienceRegions),
		pq.Array(&i.SeedKeywords),
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
