// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const addWorkflowEvent = `-- name: AddWorkflowEvent :one
INSERT INTO workflow_events (
    workflow_run_id,
    event_type,
    message,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, workflow_run_id, event_type, message, payload, created_at
`

type AddWorkflowEventParams struct {
	WorkflowRunID int64           `json:"workflow_run_id"`
	EventType     string          `json:"event_type"`
	Message       string          `json:"message"`
	Payload       json.RawMessage `json:"payload"`
}

func (q *Queries) AddWorkflowEvent(ctx context.Context, arg AddWorkflowEventParams) (WorkflowEvent, error) {
	row := q.db.QueryRowContext(ctx, addWorkflowEvent,
		arg.WorkflowRunID,
		arg.EventType,
		arg.Message,
		arg.Payload,
	)
	var i WorkflowEvent
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.EventType,
		&i.Message,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    niche_id,
    workflow_type,
    status,
    input
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, niche_id, workflow_type, status, input, output, error_message, started_at, finished_at, created_at, updated_at
`

type CreateWorkflowRunParams struct {
	NicheID      sql.NullInt64   `json:"niche_id"`
	WorkflowType string          `json:"workflow_type"`
	Status       string          `json:"status"`
	Input        json.RawMessage `json:"input"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowRun,
		arg.NicheID,
		arg.WorkflowType,
		arg.Status,
		arg.Input,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.NicheID,
		&i.WorkflowType,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, niche_id, workflow_type, status, input, output, error_message, started_at, finished_at, created_at, updated_at
FROM workflow_runs
WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id int64) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.NicheID,
		&i.WorkflowType,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowEvents = `-- name: ListWorkflowEvents :many
SELECT id, workflow_run_id, event_type, message, payload, created_at
FROM workflow_events
WHERE workflow_run_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListWorkflowEvents(ctx context.Context, workflowRunID int64) ([]WorkflowEvent, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowEvents, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowEvent{}
	for rows.Next() {
		var i WorkflowEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.EventType,
			&i.Message,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsForNiche = `-- name: ListWorkflowRunsForNiche :many
SELECT id, niche_id, workflow_type, status, input, output, error_message, started_at, finished_at, created_at, updated_at
FROM workflow_runs
WHERE niche_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowRunsForNiche(ctx context.Context, nicheID sql.NullInt64) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRunsForNiche, nicheID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.NicheID,
			&i.WorkflowType,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :one
UPDATE workflow_runs
SET
    status = $2,
    output = $3,
    error_message = $4,
    started_at = COALESCE(started_at, $5),
    finished_at = $6
WHERE id = $1
RETURNING id, niche_id, workflow_type, status, input, output, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateWorkflowRunStatusParams struct {
	ID           int64                 `json:"id"`
	Status       string                `json:"status"`
	Output       pqtype.NullRawMessage `json:"output"`
	ErrorMessage sql.NullString        `json:"error_message"`
	StartedAt    sql.NullTime          `json:"started_at"`
	FinishedAt   sql.NullTime          `json:"finished_at"`
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowRunStatus,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.NicheID,
		&i.WorkflowType,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
